test_binder:
  image: ubuntu:latest
  services:
    - docker:dind
  variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
  script:
    - apt update && apt install docker.io python3-pip -y
    - which docker
    - docker info
    - pip3 install jupyter-repo2docker
    - export VERSION=$(python3 -c "import repo2docker; print(repo2docker.__version__)")
    - echo "repo2docker version: ${VERSION}"
    - jupyter-repo2docker --debug --user-name username --user-id 1000 --no-run --image-name "${CI_PROJECT_PATH}:${CI_COMMIT_SHA}" "${CI_PROJECT_URL}"
