name: lammps-cython-environment
channels:
  - costrouc
  - conda-forge
dependencies:
  - jupyterlab_launcher
  - ipython
  - ffmpeg
  - numpy
  - matplotlib
  - lammps-cython
  - pip:
    - pymatgen
    - pybtex
